
name: Load Picture Random

on:
  schedule:
    # CHECK CODE EVERY 10 MIN
    - cron: '*/1 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Roda o arquivo
      run: |-
        node index.js
        cat README.md

    - name: Commit e push
      run: |-
        git diff
        git config --global user.email "botficalouca@email.com"
        git config --global user.name "bot automático"
        git add -A
        git commit -m "Arquivo atualizado!" || exit 0
        git pull && git push
        